logging:
  level:
    org.springframework.security: DEBUG
#
#datasource:
#  username: "root";
#  password: "12341234";
#  driverClassName: "com.mysql.cj.jdbc.Driver";
#  url: "jdbc:mysql://localhost:3306/boardservice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true";
