logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

    management:
      endpoints:
        web:
          exposure:
            include=*:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardservice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update



#
#datasource:
#  username: "root";
#  password: "12341234";
#  driverClassName: "com.mysql.cj.jdbc.Driver";
#  url: "jdbc:mysql://localhost:3306/boardservice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true";
