server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
logging:
  config: classpath:logback-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG